all:
    vars:
        ansible_connection: ssh
        ansible_user: root
        ansible_ssh_pass: root123
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    children:
        haproxy:
            hosts:
              192.168.99.11:
        webserver:
            children:
                webserver1:
                    hosts:
                      192.168.99.12:
                webserver2:
                    hosts:
                      192.168.99.13: